require("options")
require("plugins")
require("config")
require("keymaps")
require("autocmds")

-- Generated by Noctalia; missing or invalid themes must not prevent startup.
local ok, matugen = pcall(require, 'matugen')
if ok then
  pcall(function() matugen.setup() end)
end
