unbind r
bind r source-file ~/.tmux.conf

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

set -gq allow-passthrough on
set -gq allow-passthrough on

set -g mouse on

set-option -g allow-rename off

set-window-option -g mode-keys vi

set-window-option -g monitor-activity on

set -g renumber-windows on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set -s user-keys[0] "\033[250~"
set -s user-keys[1] "\033[251~"
bind-key -n User0 next-window
bind-key -n User1 previous-window

set -s user-keys[2] "\033[252~"
bind-key -n User2 switch-client -l

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'

run '~/.tmux/plugins/tpm/tpm'

set -g status-style "bg=default,fg=#cad3f5"
set -g status-left ""

set -g window-status-separator "│"
set -g window-status-style "fg=#a5adcb"
set -g window-status-format " #W "

set -g window-status-current-style "bg=default,fg=#c6a0f6"
set -g window-status-current-format " #W "

set -g window-status-activity-style "fg=#f0c6c6"

set -g status-right-length 60
set -g status-right "#[fg=#8087a2]#{pane_current_path} │ #S │ %Y-%m-%d %H:%M "
source-file -q "$XDG_CONFIG_HOME/tmux/themes/noctalia.conf"
