# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ ... }: {
	flake.nixosModules.sting-hardware = { config, lib, pkgs, modulesPath, ... }:

	{
	  imports =
		[ (modulesPath + "/installer/scan/not-detected.nix")
		];

	  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
	  boot.initrd.kernelModules = [ ];
	  boot.kernelModules = [ "kvm-amd" ];
	  boot.extraModulePackages = [ ];

	  fileSystems."/" =
		{ device = "/dev/disk/by-uuid/5c30f6e9-e4ed-4b83-b0f8-027c9033dbb4";
		  fsType = "ext4";
		};

	  fileSystems."/boot" =
		{ device = "/dev/disk/by-uuid/665C-4DA3";
		  fsType = "vfat";
		  options = [ "fmask=0022" "dmask=0022" ];
		};

	  swapDevices =
		[ { device = "/dev/disk/by-uuid/d3458b31-3115-44d3-a3c1-897ad4c5683b"; }
		];

	  boot.resumeDevice = "/dev/disk/by-uuid/d3458b31-3115-44d3-a3c1-897ad4c5683b";

	  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
	};
}
