$terminal = ghostty
$browser = zen

exec-once = [workspace 1 silent] uwsm app -- $terminal
exec-once = [workspace 2 silent] uwsm app -- $browser
exec-once = uwsm app -- waybar
exec-once = uwsm app -- hypridle
exec-once = uwsm app -- hyprpaper
exec-once = uwsm app -- mako
exec-once = uwsm app -- swayosd-server
exec-once = uwsm app -- wl-paste --watch cliphist store
exec-once = uwsm app -- sh -c '[ "$(hostname)" = glamdring ] && exec steam -tenfoot'
