$mainMod = SUPER
$terminal = ghostty
$browser = zen-browser
$fileManager = nautilus
$menu = ~/.config/rofi/launchers/type-1/launcher.sh &
$webApp = helium-browser
$floatTerm = launch-floating-terminal

bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, SPACE, exec, $menu
bind = $mainMod, C, killactive,
bind = $mainMod, M, exit,
bind = $mainMod, E, exec, $fileManager
bind = $mainMod, V, togglefloating,
bind = $mainMod, F, fullscreen
bind = $mainMod, B, exec, pkill waybar || waybar
bind = $mainMod, S, exec, hyprshot -m region
# bind = $mainMod SHIFT, S, exec, hyprshot -m window
bind = $mainMod SHIFT, L, exec, pidof hyprlock || hyprlock
bind = $mainMod, P, exec, $floatTerm pacman-install
bind = $mainMod SHIFT, P, exec, $floatTerm aur-install
bind = $mainMod, R, exec, $floatTerm pacman-remove
bind = $mainMod SHIFT, C, exec, $webApp --app=https://chatgpt.com
bind = $mainMod SHIFT, G, exec, $webApp --app=https://gemini.google.com/app
bind = $mainMod SHIFT, M, exec, $webApp --app=https://messages.google.com/web/conversations
bind = $mainMod SHIFT, D, exec, $webApp --app=https://discord.com/channels/@me
bind = $mainMod SHIFT, R, exec, $webApp --app=https://www.reddit.com/
bind = $mainMod SHIFT, S, exec, slack
bind = $mainMod SHIFT, B, exec, pkill kanata || kanata
bind = $mainMod, I, exec, pkill hypridle || hypridle
bind = $mainMod, T, exec, launch-floating-terminal-keepalive

# Move focus with mainMod + arrow keys
bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

# Switch workspaces with mainMod + [0-9]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, 0, workspace, 10

# Move active window to a workspace with mainMod + SHIFT + [0-9]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, 0, movetoworkspace, 10

bind = $mainMod, X, movecurrentworkspacetomonitor, +1

bind = $mainMod SHIFT, V, exec, cliphist list | rofi -dmenu | cliphist decode | wl-copy

# Moving and resizing windows with the mouse
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod SHIFT, mouse:272, resizewindow

# Laptop multimedia keys for volume and LCD brightness
bindel = ,XF86AudioRaiseVolume, exec, swayosd-client --output-volume=raise
bindel = ,XF86AudioLowerVolume, exec, swayosd-client --output-volume=lower
bindel = ,XF86AudioMute, exec, swayosd-client --output-volume=mute-toggle
bindel = ,XF86AudioMicMute, exec, swayosd-client --input-volume=mute-toggle
bindel = ,XF86MonBrightnessUp, exec, swayosd-client --brightness=raise
bindel = ,XF86MonBrightnessDown, exec, swayosd-client --brightness=lower

# Requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous

#bindl=,switch:Lid Switch, exec, systemctl suspend-then-hibernate
