# Extra env variables
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = PATH,$PATH:/home/james/.local/bin
env = QT_QPA_PLATFORMTHEME,qt6ct

# NVIDIA
env = ELECTRON_OZONE_PLATFORM_HINT,wayland

# env = LIBVA_DRIVER_NAME,nvidia
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia
# env = NVD_BACKEND,direct
# env = __GL_VRR_ALLOWED,0

# # One of the following caused black screen
# env = WLR_DRM_NO_ATOMIC,1
# env = __GL_GSYNC_ALLOWED,0
# env = AQ_NO_MODIFIERS,1

cursor {
	no_hardware_cursors = true
}

misc {
	vrr = 0
}
