windowrule = float on,match:class com.boondax.dial
windowrule = float on,match:class com.jfosburgh.odincraft
windowrule = float on,match:class org.netrs.ui
windowrule = match:title FloatTerm,float on
